version: '3.8'
services:
  frontend:
    build:
      context: .  # Đường dẫn đến thư mục gốc của ứng dụng
      dockerfile: Dockerfile # Tệp Dockerfile sử dụng để xây dựng image
    container_name: frontend
    image: frontend
    ports:
      - "5175:5175"
    networks:
      - network_shared


networks:
  network_shared:
    driver: bridge